import Head from 'next/head'
import Image from 'next/image'
import HeroSection from '../components/HeroSection'
import Layout from '../components/Layout'
import Partners from '../components/Partners'
import Services from '../components/Services'
import Blog from '../components/Blog'
import Teams from '../components/Teams'
import Subscribe from '../components/Subscribe'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <div className='bg-white min-h-screen text-secondary'>
      <Head>
        <title>Suppetiae</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Layout />
      <Services />
      <Partners />
     <Teams />
     <Blog />
     <Subscribe />
     <Footer />
     <div className='flex justify-center items-center mt-10 pb-10'>
                <a>
                Copyright @Suppetiae 2022. All Rights Reserved.
                </a>
            </div>
     
    </div>
  )
}
