import Head from 'next/head'
import Image from 'next/image'
import HeroSection from '../components/HeroSection'
import Navbar from '../components/Navbar'
import Partners from '../components/Partners'
import Services from '../components/Services'
import Blog from '../components/Blog'
import Teams from '../components/Teams'
import Subscribe from '../components/Subscribe'


export default function Home() {
  return (
    <div className='bg-secondary min-h-screen text-white'>
      <Head>
        <title>Suppetiae</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Navbar />
      <Services />
      <Partners />
     <Teams />
     <Blog />
     <Subscribe />
      
     
    </div>
  )
}
